name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.4'

      - name: Install dependencies
        run: bun install --no-save --check-files

      - name: Build
        run: bun run build

      - name: Publish altertable.js
        run: |
          cd packages/altertable.js
          bun publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish react-altertable.js
        run: |
          cd packages/react-altertable.js
          bun publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
