name: Release altertable.js

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.4'

      - name: Install dependencies
        run: |
          cd packages/altertable.js
          bun install --no-save --check-files

      - name: Build
        run: |
          cd packages/altertable.js
          bun run build

      - name: Publish
        run: |
          cd packages/altertable.js
          bun publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
